FROM golang:1.25-alpine AS builder
RUN apk add --no-cache git
ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /file ./cmd/file

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /file /file
COPY configs/ /configs/
EXPOSE 50055 8082
ENTRYPOINT ["/file"]
