FROM golang:1.25-alpine AS builder
RUN apk add --no-cache git
ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /relation ./cmd/relation

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /relation /relation
COPY configs/ /configs/
EXPOSE 50053
ENTRYPOINT ["/relation"]
