FROM golang:1.25-alpine AS builder
RUN apk add --no-cache git
ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /ai ./cmd/ai

FROM alpine:3.19
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /ai /ai
COPY configs/ /configs/
EXPOSE 50054 8081
ENTRYPOINT ["/ai"]
