// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	pb "lanshan11/desc" // 核心：给 desc 包起别名 pb
	"lanshan11/internal/logic"
	"lanshan11/internal/svc"
	"lanshan11/internal/types" // 导入 types 包，转换请求类型
)

// UserServer RPC服务端实现（处理注册/登录请求）
type UserServer struct {
	svcCtx                     *svc.ServiceContext
	pb.UnimplementedUserServer // 现在 pb 已定义，无报错
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// Register 实现 RPC 注册方法
func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	// 1. 转换 pb.RegisterReq → types.RegisterReq（适配 logic 层）
	req := &types.RegisterReq{
		Username: in.Username,
		Password: in.Password,
	}

	// 2. 调用 logic 层的 Register 方法
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	resp, err := l.Register(req)
	if err != nil {
		return &pb.RegisterResp{
			Code: 1,
			Msg:  err.Error(),
		}, err
	}

	// 3. 转换 types.RegisterResp → pb.RegisterResp（返回给 RPC 客户端）
	return &pb.RegisterResp{
		Code: int32(resp.Code), // int64 → int32 转换
		Msg:  resp.Msg,
	}, nil
}

// Login 补充实现 RPC 登录方法（完整）
func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	// 1. 转换 pb.LoginReq → types.LoginReq
	req := &types.LoginReq{
		Username: in.Username,
		Password: in.Password,
	}

	// 2. 调用 logic 层的 Login 方法
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	resp, err := l.Login(req)
	if err != nil {
		return &pb.LoginResp{
			Code: 1,
			Msg:  err.Error(),
		}, err
	}

	// 3. 转换 types.LoginResp → pb.LoginResp
	return &pb.LoginResp{
		Code: int32(resp.Code),
		Msg:  resp.Msg,
	}, nil
}
