# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:8
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gozerodemo
  redis:
    image: redis
    ports: ["6379:6379"]
  etcd:
    image: bitnami/etcd:3.5
    ports: ["2379:2379"]
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes